export const ADD_USER = 'ADD_USER';

export const ADD_INVENTORY = 'ADD_INVENTORY';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

export const ADD_SELLING = 'ADD_SELLING';

export const ADD_BROWSE = 'ADD_BROWSE';
export const REMOVE_BROWSE = 'REMOVE_BROWSE';
export const ADD_BROWSE_SETTINGS = 'ADD_BROWSE_SETTINGS';
export const REMOVE_BROWSE_SETTINGS = 'REMOVE_BROWSE_SETTINGS';
